### ISSUE TITLE
KdbxError: Error InvalidArg: data

### ISSUE THREAD

**Issue by ghost** [keeweb/keeweb#1141]
Hey !

**Describe the bug**
The error prevents me to open the password manager

**To Reproduce**
Just open KeeWeb and type your password.

**Expected behavior**
What it does when it works : open the password manager

**Screenshots**
![2019-03-18 16_12_28-KeeWeb – Brave](https://user-images.githubusercontent.com/26859266/54540689-b7432b80-4998-11e9-9508-7583be531c81.png)

**Environment**
I can't access settings but I use Brave Browser on Win10.
However, this error happened in the past on many other Chromium-based browsers.

**Kdbx File**
Personal data

**Logs**
```
(index):1 Document was loaded from Application Cache with manifest https://app.keeweb.info/manifest.appcache
(index):1 Application Cache Checking event
(index):1 Application Cache NoUpdate event
(index):12 2019-03-18T15:17:10.617Z [app] Started in 379ms ¯\_(ツ)_/¯
(index):12 2019-03-18T15:17:23.396Z [open:passwords_database] File open request
(index):12 2019-03-18T15:17:23.396Z [open:passwords_database] Open file from cache, will sync after load gdrive
(index):12 2019-03-18T15:17:23.397Z [storage-cache] Load be6b9849-4d06-0da3-cfe1-8415c1535eb9
(index):12 2019-03-18T15:17:23.410Z [storage-cache] Loaded be6b9849-4d06-0da3-cfe1-8415c1535eb9 1ms
(index):12 2019-03-18T15:17:23.411Z [open:passwords_database] Loaded file from cache null
(index):12 2019-03-18T15:17:23.413Z [file] Error opening file InvalidArg Error InvalidArg: data r {name: "KdbxError", code: "InvalidArg", message: "Error InvalidArg: data"}
s.error @ (index):12
(anonymous) @ (index):12
Promise.catch (async)
open @ (index):12
u @ (index):12
openFileWithData @ (index):12
(anonymous) @ (index):12
n.onsuccess @ (index):12
IndexedDB (async)
(anonymous) @ (index):12
e.onsuccess @ (index):12
IndexedDB (async)
initDb @ (index):12
load @ (index):12
load @ (index):12
openFileFromCache @ (index):12
openFile @ (index):12
requestAnimationFrame (async)
(anonymous) @ (index):12
e @ (index):12
(anonymous) @ (index):12
requestAnimationFrame (async)
(anonymous) @ (index):12
e @ (index):12
afterPaint @ (index):12
openDb @ (index):12
inputKeydown @ (index):12
M @ (index):12
(anonymous) @ (index):12
(anonymous) @ (index):12
dispatch @ (index):12
p.handle @ (index):12
(index):12 2019-03-18T15:17:23.414Z [open-view] Error opening file r {name: "KdbxError", code: "InvalidArg", message: "Error InvalidArg: data"}
s.error @ (index):12
openDbComplete @ (index):12
(anonymous) @ (index):12
t @ (index):12
(anonymous) @ (index):12
Promise.catch (async)
open @ (index):12
u @ (index):12
openFileWithData @ (index):12
(anonymous) @ (index):12
n.onsuccess @ (index):12
IndexedDB (async)
(anonymous) @ (index):12
e.onsuccess @ (index):12
IndexedDB (async)
initDb @ (index):12
load @ (index):12
load @ (index):12
openFileFromCache @ (index):12
openFile @ (index):12
requestAnimationFrame (async)
(anonymous) @ (index):12
e @ (index):12
(anonymous) @ (index):12
requestAnimationFrame (async)
(anonymous) @ (index):12
e @ (index):12
afterPaint @ (index):12
openDb @ (index):12
inputKeydown @ (index):12
M @ (index):12
(anonymous) @ (index):12
(anonymous) @ (index):12
dispatch @ (index):12
p.handle @ (index):12
```

Thanks !

**Comment by antelle** [comment]
Hi! For some reason the storage was cleaned up (I guess, some browsers do it from time to time) and we can't access it anymore. Perhaps we should give a better error message in this case.

**Comment by tianalemesle** [comment]
I clean my cache regularly.
Why does that poses a problem to KeeWeb ?

**Comment by antelle** [comment]
Perhaps we should load the file from storage in this case. For now we assume that data in IndexedDB is persistent.

**Comment by luckyrat** [comment]
The error in this issue is related to the 2nd case I describe in https://github.com/keeweb/keeweb/issues/1115#issuecomment-478240479

I have also heard of one user experience this exact error as a result of a browser crash during the local file save operation, rather than being anything to do with privacy settings. Presumably the LocalStorage change was committed to disk but IndexedDB was not.

**Comment by KaKi87** [comment]
My file is stored in Google Drive, so, how can I reload it ?

**Comment by andreasbica** [comment]
I get this issue only on iOS Safari. macOS Safari works fine! My kdbx file is stored in nextcloud.

**Comment by ottahe** [comment]
I had that issue several times, I think it was on the android 8.1 tablet always. Today I fixed it by erasing chrome's data. The database is loaded from google drive and is fine again. On other android 8.1 smartphones or windows/mac/linux desktops with the web app I've never seen that error. There was one database entry which was only visible on the tablet, after a sync it's on all devices now.

**Comment by agilgur5** [comment]
You can remove the file from the quick open list manually by clicking the 'x' on it. Then you can reload the data from source fine

**Comment by KaKi87** [comment]
I actually realized that today lol ^^
Thanks

**Comment by antelle** [comment]
Now if a file is stored on Dropbox, Google Drive, etc..., it will be opened from there if cache is not available. However if a file is stored "inside KeeWeb", it will still fail in this case.

**Comment by KaKi87** [comment]
Cached files history should simply be deleted when local storage is wiped.

**Comment by antelle** [comment]
That’s a good question if they should disappear or not. In my opinion, it’s better to show an error, so that we don’t create questions like “WTF, where’s my file???”.

**Comment by KaKi87** [comment]
Okay, but an explicit one.

`KdbxError: Error InvalidArg: data` isn't very explicit.

**Comment by antelle** [comment]
Yeah, the error message is already changed to https://github.com/keeweb/keeweb/blob/master/app/scripts/locales/base.json#L220

**Comment by KaKi87** [comment]
Maybe it would be useful to warn the user that the file will be lost if browser data is wiped until the file is saved, wathever the source is, especially when he's going to close the tab/window.

The icon left to the DB name is nice but unnoticeable if you don't have the reflex to check it.

I think I would also like an option to automatically save the file while KeeWeb is going in background or closing.

**Comment by antelle** [comment]
We do this on window/tab close, you can try :) 
Also when opening new files not from storage, there’s a warning that they can be wiped.

**Comment by KaKi87** [comment]
Nice 😁

Also tell me if there's French translation missing, I can take care of it.

**Comment by antelle** [comment]
Thank you! ❤️ 
French seems to be 100% translated, but if you would like to contribute, our translation center is here: https://keeweb.oneskyapp.com/admin/project/dashboard/project/173183 (100% of translations in KeeWeb is contributed by different volunteers).

**Comment by KaKi87** [comment]
I've done some corrections.

**Comment by antelle** [comment]
Thanks! French and German translations are fetched from OneSky and updated on every release/hotfix. Other translations are distributed as plugins and released independently.

**Comment by KaKi87** [comment]
When will the next release be released ?

**Comment by antelle** [comment]
There's [one](https://github.com/keeweb/keeweb/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.10.x) pending bugfix for v1.10.x, so probably it should be live soon, I think I'll build it tonight.
