### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by SysAlex** [keeweb/keeweb#1181]
**Describe the bug**
Multiple display of the tray icon when minimized

**To Reproduce**
1. Minimize to tray
2. Click in tray "Open KeeWeb"
3. Minimize KeeWeb
4. GoTo 1.

**Expected behavior**
One KeeWeb tray icon.

**Screenshots**
![](https://habrastorage.org/webt/uy/4n/d7/uy4nd7botbqubxfw6ze4jbt-hes.png)

**Environment**
KeeWeb 1.8.2 (ebe7d35c, 2019-04-22)
Electron v. 4.0.1

```sh
uname -a
Linux yousysadmin 4.18.0-15-generic #16~18.04.1-Ubuntu SMP Thu Feb 7 14:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by antelle** [comment]
I can still reproduce it on Ubuntu and latest Electron unfortunately. Not possible to fix until this is properly fixed: https://github.com/electron/electron/issues/17622

**Comment by SysAlex** [comment]
@antelle 
Work fine in arch linux + xfce.
The problem only in the gnome environment (tested in ubuntu & centos7).

**Comment by antelle** [comment]
Yes, although we call [tray.destroy](https://electronjs.org/docs/api/tray#traydestroy), it doesn't get destroyed. Actually we don't have any other control over this tray icon apart from calling this method, so it will be there for some time until it's fixed in Electron.

**Comment by antelle** [comment]
The bot was misconfigured, sorry for a wrong notification.

**Comment by aleskandro** [comment]
HI, it appears that electron has fixed this bug on version >=7.0.0 which are the one used on this project (https://github.com/electron/electron/pull/18196). However this bug is still happening on Gnome (Fedora 31). I tried to update electron version from 7.0.0 to 7.1.0 but nothing changes

**Comment by YouSysAdmin** [comment]
I solved this problem cardinally - I deleted the Gnome.
No Gnome, no problem :)

_P.S. Perfectly working in the i3wm_

**Comment by hitodev** [comment]
Same problem with Ubuntu 20.04 LTS
---
KeeWeb v1.15.6 (af49645, 2020-08-08)
Environment: electron v9.0.4
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.15.6 Chrome/83.0.4103.104 Electron/9.0.4 Safari/537.36

The problem doesn't exist on Ubuntu 20.10 Groovy

**Comment by 3mb3dw0rk5** [comment]
A solution could be to keep the tray icon also when the app is activated. There is actually no need to remove the tray icon when the app window is opened.

**Comment by julianfairfax** [comment]
> A solution could be to keep the tray icon also when the app is activated. There is actually no need to remove the tray icon when the app window is opened.

@antelle Ths is how other apps do it and it works correctly. Can you implement this and fix this issue?

**Comment by el3ctrician** [comment]
Hello, 
any updates regarding the issue ? still present in ubuntu 21.04... how can I help :) ?

**Comment by KaikiasVind** [comment]
Yes, still present, for me on fedora 35.

**Comment by viktordw** [comment]
I still have the same problem on Cinnamon. Is there any news about this?

**Comment by YouSysAdmin** [comment]
Sorry, I haven't been using KeeWeb for a long time, and this issue keeps hanging in my open issues list.
With your permission, I'll close it :)
