### ISSUE TITLE
Global auto-type (alt+shift+t) does not invoke keeweb

### ISSUE THREAD

**Issue by elbowz** [keeweb/keeweb#1421]
**Describe the bug**
Using shortcut alt+shift+T nothing happens. but if I select keeweb app appear the message:

*Auto-type error*
*to use system-wide shortcuts, please focus the app...*

**To Reproduce**
1. Focus chrome with a login page
2. Click on alt+shift+T

**Expected behavior**
Auto-typing/filling the login form or the keeweb selection list (if not match with window title)

**Screenshots**
![Animated GIF](https://user-images.githubusercontent.com/1451484/76164488-acf0e300-614f-11ea-9a85-3e43ff8863b2.gif)

**Environment**
KeeWeb v1.12.3 (9b07bbd5, 2019-12-26)
Environment: electron v8.0.2
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.12.3 Chrome/80.0.3987.86 Electron/8.0.2 Safari/537.36

**Logs**
```
2020-03-08T14:23:54.710Z [sync:keepass] Sync finished no error
2020-03-08T14:24:46.748Z [auto-type] Auto type event null
```

p.s. can be implemented an auto-type matching with a dedicated field (better regex) to match with the window title? Now it have to match only with entry title

**Comment by antelle** [comment]
Hi! Does the app start now? If yes, let's see what you have in logs

**Comment by elbowz** [comment]
yeah...updated the post

**Comment by antelle** [comment]
Is there anything after it?

**Comment by antelle** [comment]
Another way to debug is to open devtools, run this:
```
localStorage.debugAutoType = 1
```
and reload the page from devtools, this should give more logs.

**Comment by elbowz** [comment]
No more verbose log...also enabling the debugAutoType as you can see
```
2020-03-08T14:44:40.582Z [sync:keepass] Sync finished no error
2020-03-08T14:44:51.786Z [auto-type] Auto type event null
localStorage.debugAutoType
"1"
```
I guess the SO don't "pass" the shortcut alt+shift+t to keeweb. 
I think this because when i focous keeweb instantly the "Auto-type error" appear, so finally the shortcut is catched.

**Comment by antelle** [comment]
They don't appear immediately, you need to reload the window after doing the `debugAutoType` thing.

**Comment by antelle** [comment]
The "Auto-type error" happens when you press the shortcut in keeweb, that's how it's supposed to work.

**Comment by elbowz** [comment]
@antelle I have done reload by F5. The log don't change.

**Comment by antelle** [comment]
Have you triggered auto-type in browser after reloading?

**Comment by elbowz** [comment]
> Have you triggered auto-type in browser after reloading?

Of course...why set debug variable and reload if not replicate the bug  and store the log :)

**Comment by antelle** [comment]
Not good, thanks for trying it so many times! I'm very sorry that it's so broken for you, but I can't help from here. If you have any other details, please add a comment. At the moment I don't see a way to help or debug.

**Comment by elbowz** [comment]
Thanks for you speedy answers...I prefer to spent your time to fix the #1359 (I cannot synch anymore on gdrive)...

What about the "p.s." the main topic of this issue?

Do you thin is possible to fine a dedicated field with a regex for match the window title (if ever auto-type re-start working)

**Comment by antelle** [comment]
Google Drive issues should be fixed in the next release, it happens quite often now, yes.
About more flexible auto-type, it's mentioned in https://github.com/keeweb/keeweb/issues/433

**Comment by elbowz** [comment]
Really thanks!!

**Comment by EwoutWal** [comment]
I am having the same issue on Manjaro Linux with KDE where auto-type tends to fail on the alt+shift+t key combination. I have noticed that if I do nothing for 5-10 seconds after pressing the key combination that it does invoke auto-type correctly. When I switch to the KeeWeb desktop application within that time frame, the error message is shown and auto-type is not run. It seems as if the key combination does not get registered by the KeeWeb application right away unless I focus it (at which point this is a very logical error to display).

**Comment by elbowz** [comment]
same behaviour...but the delay time of 5-10 seconds not always works.

I have found a very bad workaround:
1. focus the chrome/browser windows where you want login
2. invoke the shortcut ctrl+alt+t
3. speedily move the mouse cursor on keeweb (giving the focus) and come back on login page

It works, but some times, as you can guess the first characters of username was trimmed out.

I think definitely is the global shortcut registration (of electron?) not works anymore (on KDE?)

**Comment by jivarson** [comment]
same here, ubuntu 19.10 (which uses GNOME 3.34.2).
problem remains in 1.13.2

**Comment by vetko** [comment]
I have the same issue on **KDE** (openSUSE Tumbleweed): Global Autotype does not invoke KeeWeb properly, instead if I focus KeeWeb manually then I get the error: "Auto-type error - to use system-wide shortcuts, please focus the app..."
Might be important to know:
- It only started after the **v1.13.0** release, it was **working perfectly before**
- Being on the latest versions now (v1.13.3 - v1.14.0), the issue only appears **if KeeWeb is minimized to dock**, but it works properly if KeeWeb is simply minimized to the taskbar.
- Between the v1.13.0 - v1.13.3 releases I had the issue even if KeeWeb was minimized to the taskbar (but that is fixed now)

**Comment by LennartCockx** [comment]
I also have this issue on **Fedora 32** with **v1.14.2**

- Enable 'Minimize the app instead of close'
- Close the application (shown as running in the gnome top bar)
- Perform Global auto-type (shift+alt+t) 
- Nothing happens (Auto-type error is shown when maximizing KeeWeb again)

Auto-type works perfectly when application is minimized normally (not to tray)

**Comment by bdeeming** [comment]
I can confirm that exactly the same as described by @LennartCockx occurs on plain Ubuntu 20.04, fresh install.

**Comment by markojurkovic** [comment]
I can also confirm the issue on a fresh install of Pop OS 20.04, but it happens regardless of what state the app is in -- minimized to tray, minimized regularly, or even if the window is open in the background.
