### ISSUE TITLE
Can't run KeeWeb

### ISSUE THREAD

**Issue by menchold** [keeweb/keeweb#1561]
I started the computer this morning and I got this bug. Yesterday and today I didn't install any software, there were no changes in the system, so I don't know where this message came from.

Recently I had the same situation after reinstalling the system, so I did it again - this solved the problem, but as you can see, only temporarily.

`Error loading app: Error reading config data app-settings: Error: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT`

**Comment by menchold** [comment]
Somebody can help me?

**Comment by antelle** [comment]
Hi! Which operating system are you on?
To fix this immediately, you can open KeeWeb by deleting app-settings.dat (and other .dat files) located in the app data directory, but I'm curious why this is happening.

**Comment by thib3113** [comment]
same error, I just reinstall windows ( windows 10 pro 2004 ), and try to reinstall keeweb, but it fail with same error .

**Comment by antelle** [comment]
@thib3113 was it a fresh installation, or you restored a sort of backed up? do you have any .dat files in AppData/KeeWeb?

**Comment by thib3113** [comment]
> @thib3113 was it a fresh installation, or you restored a sort of backed up? do you have any .dat files in AppData/KeeWeb?

fresh install of windows, but yes I backed and restore the AppData folder (not all, but some folders) .

But, I didn't have custom version of openSSL or things like that :) . ( and I totally understand that backup/restoring the appData is not handled by keeweb, no problem )

**Comment by antelle** [comment]
Let me explain how it works. When KeeWeb is run for the first time, it:
1. generates a key and stores it in the system keychain (that was not restored from the backup)
2. encrypts its settings and saves them to AppData/app-settings.dat
Now you restored the .dat file, however when KeeWeb tries to find a key, it can't, because the keychain doesn't contain the key. Probably in this case we should just ignore the data in AppData and behave as if it was a new installation. Maybe ask a question, I'll think how to handle that.

**Comment by thib3113** [comment]
Or maybe throwing an error "more readable" ?

Like "fail to read the key in the keychain, can't decrypt settings" ? (not sure decrypt is the correct word in english)

**Comment by cengizIO** [comment]
Any readers having this problem on Windows, you can reset your KeeWeb Desktop settings by:

1. Go to Start Menu
2. type `%AppData%` and press Enter
3. Go into `KeeWeb` directory.
4. Delete `app-settings.dat`

**Comment by philippemilink** [comment]
Just for the record, I got the same error on Debian10, and I just fixed the error as suggested here: deleting app-settings.dat (I kept a backup of the buggy file if you need it to investigate).

**Comment by antelle** [comment]
I don't need it, thanks, it's perfectly clear why it happens. In all cases KeeWeb was launched from another user, or with deleted user data. So, the next version will backup app-settings.dat and other files in this case and create new ones, without the error message.

**Comment by richardneililagan** [comment]
> You said you have the same issue, right? It complains about reading the config.
> If so, I’m very interested what could lead to it.

@antelle on an OSX, and deleting `app-settings.dat` definitely fixed it. 

To provide context on how it happened though, I had to recreate my keychain due to some circumstances, and that pretty much did it for me.

**Comment by mundo03** [comment]
on linux, delete ```~/.config/KeeWeb``` folder

**Comment by benben-ops** [comment]
New Installation on Ubuntu 20.04.3 LTS. 
Start after install asks for password but with this message:
The password you use to login to your computer no longer matches that of your key ring.
The app does not take any password and after cancel crash with this error:  Cannot create an item in a locked collection.
............
To delete ~/.config/KeeWeb folder does not resolve problem.

any advice?
Thanx

**Comment by alemuntoni** [comment]
Hi, I have the same issue: cannot start KeeWeb. It shows the error when launching the app:
```
Error: Cannot create an item in a locked collection.
```
I am on Ubuntu running wayland (could be the cause?).
Tried both the deb and the AppImage, removing the `.config/KeeWeb` directory. Nothing changed.
I also tried to disable the fingerprint authentication just to be sure that wasn't the problem, but did not work.

**Comment by alemuntoni** [comment]
Fast update: I managed to finally have KeeWeb working, by doing the following actions:
- remove the snap package of firefox (installed by default on recent versions of ubuntu)
- install the debian package of firefox

I don't know if there is some hidden-dependency.. Hope this helps!
Thanks for the great software! :)
