### ISSUE TITLE
In-app update fails on macOS Big Sur (Intel)

### ISSUE THREAD

**Issue by lausvi** [keeweb/keeweb#1767]
**Describe the bug**
Updating within the app fails. This has now been happing to me for couple of past versions (perhaps for 2-3 months). I've just manually installed new versions, but I guess this should be reported :)

**To Reproduce**
Click 'Download update and restart'
KeeWeb window closes, but an error window pops up with 'Error -1743'. (The finnish part just says 'error happened').
<img width="324" alt="keeweb_error" src="https://user-images.githubusercontent.com/44120964/112720204-a45b7e00-8f05-11eb-83fa-647d8b64bd78.png">

If I click OK, app stays open in the dock, but is not responding and must be force quit. Opening it again brings back the old, still working version (and retrying the update makes it fail exactly the same way).
 
If I click Muokkaa (Edit) -> Mac Script editor starts with KeeWeb Installer window.
<img width="717" alt="keeweb_error2" src="https://user-images.githubusercontent.com/44120964/112720205-a6254180-8f05-11eb-82e0-df99998ade79.png">

**Environment**
KeeWeb v1.17.3 (0d2107e, 2021-03-14)
Environment: electron v12.0.0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.17.3 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36

**Kdbx File**
DB on Dropbox.

**Logs**
Show app logs has these:
[ERROR] 2021-03-27T12:02:11.276Z [plugin-gallery] JSON signature invalid
[ERROR] 2021-03-27T12:02:11.276Z [plugin:keewebhttp] Manifest validation error Public key mismatch

**Comment by antelle** [comment]
Hi! Do you have minimize on close setting enabled?

**Comment by lausvi** [comment]
Hi, that was quick :) 
No, it's not enabled.

**Comment by antelle** [comment]
Interesting. Does it maybe show the line with error in the editor? Not sure if this will work, but maybe if you click the "play" button it will show more details?

**Comment by lausvi** [comment]
Clicked play: Script error: Error: Unknown operation. Then it shows in the log window: Error -2700: Script error.

Can't seem to find any indication on what or where it happens, though.

**Comment by antelle** [comment]
Interesting, then I'll need some help from you because it doesn't give this error for me. Would you mind running the installer script if I add some debugging logs to it?

**Comment by lausvi** [comment]
Sure 👍

**Comment by antelle** [comment]
Ok, thank you! I'll prepare the script today and post it here.

**Comment by antelle** [comment]
I've added `--verbose` option to the installer: https://github.com/keeweb/keeweb/blob/develop/package/osx/installer.js

1. Download this script and the dmg:

```sh
curl -OSsL https://github.com/keeweb/keeweb/releases/download/v1.17.5/KeeWeb-1.17.5.mac.x64.dmg
curl -OSsL https://raw.githubusercontent.com/keeweb/keeweb/develop/package/osx/installer.js
```

2. Open the dmg, copy KeeWeb.app from here next to the dmg, this will be the test app that we'll use for updating.
3. Launch KeeWeb.app
4. Run the installer:

```sh
osascript -l JavaScript installer.js --verbose --update --dmg=$(pwd)/KeeWeb-1.17.5.mac.x64.dmg --app=$(pwd)/KeeWeb.app
```

It should update the downloaded KeeWeb.app.

Meanwhile I think I've found the error, but I'd like to confirm my hypothesis.

**Comment by lausvi** [comment]
Ok, did your test procedure and it worked! 💯 👍

**Comment by antelle** [comment]
Hm, that's not very good, because I expected that it would give an error, so it's not confirmed that the fix fixed it.

**Comment by antelle** [comment]
Ok, I'll release the fix in the next KeeWeb version and if that version can't update, we can continue looking into it, but most likely it will be fixed. Thanks for reporting it!

**Comment by antelle** [comment]
The fix is released. Please [download](https://github.com/keeweb/keeweb/releases/v1.17.6) this version and then, if updating _from_ this version to the next one throws an error, let me know!

**Comment by willvousden** [comment]
@antelle Still getting this problem with v1.18.6!

**Comment by antelle** [comment]
@willvousden  is the error the same?

**Comment by willvousden** [comment]
@antelle Yep, identical.

**Comment by lausvi** [comment]
Sorry for not bringing this up earlier, but I also still have the same problem. For some time I didn't remember to update, or I did it by GitHub's email links (downloaded new version instead of updating in-app) so I didn't remember the issue. Still the exact same error.
