### ISSUE TITLE
Can not open KeeWeb from ubuntu 16.04 anymore

### ISSUE THREAD

**Issue by bastos77** [keeweb/keeweb#678]
Today I successfully opened and worked with KeeWeb. But now, when I try to open my .kdbx file there was the following error: "TypeError: Cannot read property 'id' of undefined"

Is this a bug or is the file corrupt

**Comment by antelle** [comment]
Hi,
Can you open this file with:
- online version, app.keeweb.info?
- other keepass clients?

Could you please expand the error and post the stack trace here?

**Comment by bastos77** [comment]
Hi.
Thank you for your support!

- I can open the demo.
- I added a encrypted test.kdbx and able to open it again.
- I can open the demo in app.keeweb.info
- but unfortunately the my .kdbx I can not open online. It states "Beim Öffnen der Datei ist ein Fehler aufgetreten TypeError: e.uuid is undefined"

Where can I find the stack trace? Or KeeWeb logs? Than I can upload it.

**Comment by antelle** [comment]
The logs are in browser dev console, you can open it with `⌘F12` or `Ctrl+F12`. In browser, it depends, but it's standard browser devtools.
Then you will be able to expand the error.

**Comment by bastos77** [comment]
I use Firefox in ubuntu 16.04. Do you mean the "Konsole" output?
2017-07-10T16:29:20.052Z [open:Sebastian] File open request  app.keeweb.info:14:897
2017-07-10T16:29:20.053Z [open:Sebastian] Open file from supplied content  app.keeweb.info:14:897
2017-07-10T16:29:20.147Z [file] Error opening file undefined e.uuid is undefined TypeError: e.uuid is undefined
Stack-Trace:
setGroup/<@https://app.keeweb.info/:15:2688
setGroup@https://app.keeweb.info/:15:2654
c.fromGroup@https://app.keeweb.info/:15:6844
setGroup/<@https://app.keeweb.info/:15:2624
setGroup@https://app.keeweb.info/:15:2518
c.fromGroup@https://app.keeweb.info/:15:6844
readModel/<@https://app.keeweb.info/:17:13127
readModel@https://app.keeweb.info/:17:13026
open/</<@https://app.keeweb.info/:17:10600
  app.keeweb.info:14:1219
2017-07-10T16:29:20.149Z [open-view] Error opening file TypeError: e.uuid is undefined
Stack-Trace:
setGroup/<@https://app.keeweb.info/:15:2688
setGroup@https://app.keeweb.info/:15:2654
c.fromGroup@https://app.keeweb.info/:15:6844
setGroup/<@https://app.keeweb.info/:15:2624
setGroup@https://app.keeweb.info/:15:2518
c.fromGroup@https://app.keeweb.info/:15:6844
readModel/<@https://app.keeweb.info/:17:13127
readModel@https://app.keeweb.info/:17:13026
open/</<@https://app.keeweb.info/:17:10600
  app.keeweb.info:14:1219

**Comment by antelle** [comment]
Yes, exactly.
So, we have something strange inside a group. Do you have an idea what could've caused it? E.g. your last actions in keeweb?

**Comment by bastos77** [comment]
The last major action has been, that I attached a small excel file...

**Comment by bastos77** [comment]
Should I try to open the file with an other program? Like KeePass2?

**Comment by bastos77** [comment]
That worked! I have been able to open the file with KeePass2 (2.3.2 Dev) on ubuntu 16.04

**Comment by antelle** [comment]
The database could be still a little bit broken. Is it possible to open it in keeweb after you save it?

**Comment by bastos77** [comment]
> Is it possible to open it in keeweb after you save it? <
Yes :-))))))))))))

**Comment by antelle** [comment]
Cool, however I can't understand why it could happen. If you can repeat it on a new file, it would be very helpful.

**Comment by dzek69** [comment]
I just had similiar problem. `Cannot read property 'id' of undefined.` with this in console:
```
[open:work] File open request
[open:work] Open file from cache, will sync after load gdrive
[storage-cache] Load 4ae056a5-f74d-3972-5ff0-c0cdb76e6aff
[storage-cache] Loaded 4ae056a5-f74d-3972-5ff0-c0cdb76e6aff 13ms
[open:work] Loaded file from cache null
[file] Error opening file undefined Cannot read property 'id' of undefined TypeError: Cannot read property 'id' of undefined(…)o.error @ index.html:14(anonymous function) @ index.html:17
index.html:14 2017-07-19T08:35:57.924Z
[open-view] Error opening file TypeError: Cannot read property 'id' of undefined(…)o.error @ index.html:14openDbComplete @ index.html:24(anonymous function) @ index.html:19l @ index.html:19(anonymous function) @ index.html:17
```
I'm thinking about this `null` in `[open:work]` and later `opening file undefined`.

I'm using Google Drive.

What I did yesterday that caused the issue:
Edited one simple login-password entry bunch of times. Then I saved copy of one of history items of that entry. Then I modified the entry once again.

I was not able to repeat that on clean file.

Opening "broken" file with KeePassX, saving it there and reopening in KeeWeb fixed the issue.

OS: Linux 64bit
App: Desktop, broken on 1.5.2, updated to 1.5.4 with no luck with opening

Did not try with web version.

Trying to reproduce the issue was on 1.5.4, so there is a chance it got fixed somehow in the meantime.

**Comment by antelle** [comment]
1.5.2 had some related bug, maybe the same happened in the original report? If you manage to repeat in 1.5.4, please let me know. I mean, opening will not work, but why this could happen, that's an interesting question. Might be the same as #652, which is now fixed.

**Comment by davidroeca** [comment]
I'm still encountering this issue from time to time.

Some additional info:
* I'm using Dropbox to sync the file.
* I use the iPhone app [Keepass Touch](https://apps.apple.com/us/app/keepass-touch/id966759076) to sync the file there--I'm successfully able to edit the file from there and re-sync to fix the problem.
* I run `KeeWeb` on Linux Mint 19 (which is based on Ubuntu 16.04).

KeeWeb info:
```
KeeWeb v1.8.2 (ebe7d35c, 2019-04-22)
Environment: electron v4.0.1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.8.2 Chrome/69.0.3497.106 Electron/4.0.1 Safari/537.36
```
