### ISSUE TITLE
Security Exception at local Plugin/Import isn't ignored

### ISSUE THREAD

**Issue by xieve** [keeweb/keeweb#820]
I generated a little theme to match colors to my OS. I followed the instruction until firefox wouldn't let me save the exception rule permanently:
![image](https://user-images.githubusercontent.com/20223093/34326198-868927b8-e8a7-11e7-961b-0562a69496e9.png)
When I tried clicking "Confirm security exception", it would just do nothing. It only worked when I unchecked "Permanently store this exception". Obviously this wasn't what I wanted, because that lead to this, when trying to import the theme:
```
2017-12-24T11:31:05.948Z [plugin] Installing plugin from url https://127.0.0.1:8089/
index.html:1605 2017-12-24T11:31:05.949Z [plugin] GET https://127.0.0.1:8089/manifest.json?ts=1514115065949
https://127.0.0.1:8089/manifest.json?ts=1514115065949 Failed to load resource: net::ERR_INSECURE_RESPONSE
index.html:1605 2017-12-24T11:31:06.000Z [plugin] GET error https://127.0.0.1:8089/manifest.json?ts=1514115065949 0
index.html:1629 2017-12-24T11:31:06.000Z [plugin] Error loading plugin manifest network error
  Logger.error @ index.html:1629
```
So I tried importing it like this:
![image](https://user-images.githubusercontent.com/20223093/34326342-5a7eaf32-e8aa-11e7-9fde-1e1f2c19c124.png)
_Here, the theme's already applied._
That did work, tho when I restarted keeweb, this happened:
![image](https://user-images.githubusercontent.com/20223093/34326364-d96f84a6-e8aa-11e7-8ebf-9345275bc852.png)
1. The colors were corrupted
2. The Addon suddenly became invalid, this is the console line probably explaining why: `[plugin:my-theme] Manifest validation error Public key mismatch`

**Comment by antelle** [comment]
Since the latest KeeWeb, you cannot permanently install plugins signed by third-party keys, so this is expected.
Well, maybe in Firefox it doesn't work, if you confirm a security exception and choose to save it permanently.
How did you manage to load your plugin? Did it work when you used `file:///`?
Another question, how did you load KeeWeb? Using the official app (app.keeweb.info) or stored on your local file?
Probably plugin should provide hosted version KeeWeb as well, I'll add it.

**Comment by antelle** [comment]
Fixed, now plugin server will serve KeeWeb and config. So, if you go to `https://127.0.0.1:8089`, you will see KeeWeb with the plugin already loaded inside.

**Comment by xieve** [comment]
@antelle 

> you cannot permanently install plugins signed by third-party keys

So I gotta create my own keypair manually, or what? This isn't mentioned on the wiki page I think.

> How did you manage to load your plugin? Did it work when you used `file:///`?

Yes, it did, I mentioned that.

> Another question, how did you load KeeWeb? Using the official app (app.keeweb.info) or stored on your local filesystem?

Stored on my local filesystem, using the launcher thingy, not a real browser.

**Comment by antelle** [comment]
There are three ways to add a permanent plugin to KeeWeb:
1. self-host KeeWeb and add a config with this plugin
2. to develop&test, this is already done in keeweb-plugin, so if you run `keeweb-plugin watch ...`, it will give you the url where to go with your plugin installed
3. for app.keeweb.info and desktop apps, submit your plugin as a PR here: https://github.com/keeweb/keeweb-plugins

**Comment by xieve** [comment]
Soo now that that's fixed I can do the same as I tried and it will work permanently? Damn that sounds stupid, even for a more rethorical question. Thanks, I guess. No, wait: it still won't work, will it? Shall I use another browser than Firefox? Or is it simpler just to locate the config? I'm currently usimg this on my desktop and it soon will be self-hosted on my little vServer.

**Comment by antelle** [comment]
I don't quite understand you, sorry. Please correct me if I got something wrong.
> that's fixed 

You mean the issue status? I've implemented a simple way to test plugins in keeweb-plugin, so it doesn't require these complicated steps to test now: just run `keeweb-plugin watch` and that's it. Everything else is the same.
> I can do the same as I tried and it will work permanently?

There are three ways to make the plugin permanent, as described in my previous comment.
> It still won't work, will it?

Depends on what you want, so I'm not sure if that's it.
> Or is it simpler just to locate the config?

Yes, if you're going to use a plugin on your self-hosted installation, you will need a config for that.

**Comment by xieve** [comment]
Okay, I'm the one who should be sorry and I am. What I want: A permanent plugin. Where I want it: In my desktop non-web linux app. I misunderstood, sorry again, let's just forget that. Now, what I wanted to ask was: does this work for me too, without really hosting it? I suppose so, but I'm not sure and also I can't find any configuration option that does this. Am I being stupid or is that missing?

**Comment by antelle** [comment]
I see, yeah, it's a problem.
For now, the only way to make a permanent plugin for apps is to submit it to plugins.keeweb.info.
I'm still thinking how to make it possible without a security risks. The thing is, if we allow unsigned plugins, any app can add a plugin to your keeweb and do whatever it wants. It should be solved with permissions, e.g. add a list of additional allowed keys somewhere, probably it will be there in the next version.

**Comment by xieve** [comment]
Nice! Thanks.
